import React from 'react';
import ReactDOM from 'react-dom/client';

function Kyrgios(){
    return(
        <div className="item-container">
            <div className="card">
                <img src={`${process.env.PUBLIC_URL}/assets/kyrgios.svg`} alt="Nick Kyrgios" />
                <p>Nick Kyrgios</p>
                <div className="infos-card">
                    <p>Right-Hander</p>
                    <p>Serve-Volley</p>
                    <p>Unlocked in Tour 3 and above</p>
                    <div className="nationality">
                        <img className="flag" src={`${process.env.PUBLIC_URL}/assets/australia.svg`} alt="Australia"/>
                        <p>Australia</p>
                    </div>
                </div>
            </div>
            <div className="table-container">
                <table className="kyrgios">
                    <caption>Kyrgios's Upgrade Table</caption>
                    <thead>
                        <tr>
                            <th>Level</th>
                            <th>1</th>
                            <th>2</th>
                            <th>3</th>
                            <th>4</th>
                            <th>5</th>
                            <th>6</th>
                            <th>7</th>
                            <th>8</th>
                            <th>9</th>
                            <th>10</th>
                            <th>11</th>
                            <th>12</th>
                            <th>13</th>
                            <th>14</th>
                            <th>15</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Up Cards</td>
                            <td></td>
                            <td>2</td>
                            <td>3</td>
                            <td>4</td>
                            <td>5</td>
                            <td>6</td>
                            <td>8</td>
                            <td>10</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Price Upgrade</td>
                            <td></td>
                            <td>6K</td>
                            <td>11K</td>
                            <td>36K</td>
                            <td>52K</td>
                            <td>140K</td>
                            <td>180K</td>
                            <td>440K</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
                <table className="kyrgios">
                    <caption>Kyrgios's Skills Table</caption>
                    <thead>
                        <tr>
                            <th>Level</th>
                            <th>1</th>
                            <th>2</th>
                            <th>3</th>
                            <th>4</th>
                            <th>5</th>
                            <th>6</th>
                            <th>7</th>
                            <th>8</th>
                            <th>9</th>
                            <th>10</th>
                            <th>11</th>
                            <th>12</th>
                            <th>13</th>
                            <th>14</th>
                            <th>15</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Agility</td>
                            <td>5</td>
                            <td>6</td>
                            <td>8</td>
                            <td>10</td>
                            <td>11</td>
                            <td>13</td>
                            <td>15</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>28</td>
                        </tr>
                        <tr>
                            <td>Stamina</td>
                            <td>3</td>
                            <td>4</td>
                            <td>4</td>
                            <td>5</td>
                            <td>6</td>
                            <td>6</td>
                            <td>7</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>12</td>
                        </tr>
                        <tr>
                            <td>Serve</td>
                            <td>7</td>
                            <td>8</td>
                            <td>10</td>
                            <td>11</td>
                            <td>13</td>
                            <td>14</td>
                            <td>15</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>27</td>
                        </tr>
                        <tr>
                            <td>Volley</td>
                            <td>6</td>
                            <td>8</td>
                            <td>9</td>
                            <td>10</td>
                            <td>12</td>
                            <td>13</td>
                            <td>15</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>25</td>
                        </tr>
                        <tr>
                            <td>Forehand</td>
                            <td>7</td>
                            <td>8</td>
                            <td>9</td>
                            <td>11</td>
                            <td>12</td>
                            <td>13</td>
                            <td>15</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>25</td>
                        </tr>
                        <tr>
                            <td>Backhand</td>
                            <td>4</td>
                            <td>5</td>
                            <td>7</td>
                            <td>8</td>
                            <td>9</td>
                            <td>10</td>
                            <td>11</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>19</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Total Power</th>
                            <th>32</th>
                            <th>39</th>
                            <th>47</th>
                            <th>55</th>
                            <th>63</th>
                            <th>69</th>
                            <th>78</th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>136</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    );
}

export default Kyrgios;