import React from 'react';
import ReactDOM from 'react-dom/client';

function Hope(){
    return(
        <div className="item-container">
            <div className="card">
                <img src={`${process.env.PUBLIC_URL}/assets/hope.svg`} alt="Hope" />
                <p>Hope</p>
                <div className="infos-card">
                    <p>Right-Hander</p>
                    <p>All-Around</p>
                    <div className="nationality">
                        <img className="flag" src={`${process.env.PUBLIC_URL}/assets/usa.svg`} alt="USA"/>
                        <p>USA</p>
                    </div>
                </div>
            </div>
            <div className="table-container">
            <table className="hope">
                <caption>Upgrade Table</caption>
                <thead>
                    <tr>
                        <th>Level</th>
                        <th>1</th>
                        <th>2</th>
                        <th>3</th>
                        <th>4</th>
                        <th>5</th>
                        <th>6</th>
                        <th>7</th>
                        <th>8</th>
                        <th>9</th>
                        <th>10</th>
                        <th>11</th>
                        <th>12</th>
                        <th>13</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Up Cards</td>
                        <td></td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>8</td>
                        <td>10</td>
                        <td>20</td>
                        <td>40</td>
                        <td>60</td>
                        <td>100</td>
                        <td>200</td>
                        <td>600</td>
                        <td>1000</td>
                        <td>2000</td>
                    </tr>
                    <tr>
                        <td>Price Upgrade</td>
                        <td></td>
                        <td>400</td>
                        <td>1.4K</td>
                        <td>3.2K</td>
                        <td>6K</td>
                        <td>11K</td>
                        <td>17.2K</td>
                        <td>26K</td>
                        <td>36K</td>
                        <td>52K</td>
                        <td>66K</td>
                        <td>110K</td>
                        <td>250K</td>
                        <td>800K</td>
                        <td>2M</td>
                    </tr>
                </tbody>
            </table>
            <table className="hope">
                <caption>Skills Table</caption>
                <thead>
                    <tr>
                        <th>Level</th>
                        <th>1</th>
                        <th>2</th>
                        <th>3</th>
                        <th>4</th>
                        <th>5</th>
                        <th>6</th>
                        <th>7</th>
                        <th>8</th>
                        <th>9</th>
                        <th>10</th>
                        <th>11</th>
                        <th>12</th>
                        <th>13</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Agility</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>11</td>
                        <td>12</td>
                        <td>13</td>
                        <td>14</td>
                        <td>15</td>
                        <td>16</td>
                        <td>17</td>
                    </tr>
                    <tr>
                        <td>Stamina</td>
                        <td>4</td>
                        <td>4</td>
                        <td>5</td>
                        <td>5</td>
                        <td>6</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>8</td>
                        <td>9</td>
                        <td>9</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                    </tr>
                    <tr>
                        <td>Serve</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                        <td>13</td>
                        <td>14</td>
                        <td>15</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <td>Volley</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                    </tr>
                    <tr>
                        <td>Forehand</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                        <td>13</td>
                        <td>16</td>
                        <td>18</td>
                        <td>19</td>
                        <td>20</td>
                        <td>21</td>
                        <td>22</td>
                        <td>23</td>
                    </tr>
                    <tr>
                        <td>Backhand</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                        <td>13</td>
                        <td>14</td>
                        <td>15</td>
                        <td>16</td>
                        <td>17</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Total Power</th>
                        <th>27</th>
                        <th>32</th>
                        <th>38</th>
                        <th>42</th>
                        <th>48</th>
                        <th>53</th>
                        <th>61</th>
                        <th>68</th>
                        <th>73</th>
                        <th>78</th>
                        <th>83</th>
                        <th>89</th>
                        <th>95</th>
                    </tr>
                    <tr>
                        <td>Up Cards</td>
                        <td></td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>8</td>
                        <td>10</td>
                        <td>20</td>
                        <td>40</td>
                        <td>60</td>
                        <td>100</td>
                        <td>200</td>
                        <td>600</td>
                    </tr>
                    <tr>
                        <td>Price Upgrade</td>
                        <td></td>
                        <td>400</td>
                        <td>1.4K</td>
                        <td>3.2K</td>
                        <td>6K</td>
                        <td>11K</td>
                        <td>17.2K</td>
                        <td>26K</td>
                        <td>36K</td>
                        <td>52K</td>
                        <td>66K</td>
                        <td>110K</td>
                        <td>250K</td>
                    </tr>
                </tfoot>
            </table>
            </div>
        </div>
    );
}

export default Hope;
