import React from 'react';
import ReactDOM from 'react-dom/client';

function MeiLi(){
    return(
        <div className="item-container">
            <div className="card">
                <img src={`${process.env.PUBLIC_URL}/assets/mei-li.svg`} alt="Mei-Li" />
                <p>Mei-Li</p>
                <div className="infos-card">
                    <p>Right-Hander</p>
                    <p>All-Around</p>
                    <div className="nationality">
                        <img className="flag" src={`${process.env.PUBLIC_URL}/assets/china.svg`} alt="china"/>
                        <p>China</p>
                    </div>
                </div>
            </div>
            <div className="table-container">
            <table className="mei-li">
                <caption>Upgrade Table</caption>
                <thead>
                    <tr>
                        <th>Level</th>
                        <th>1</th>
                        <th>2</th>
                        <th>3</th>
                        <th>4</th>
                        <th>5</th>
                        <th>6</th>
                        <th>7</th>
                        <th>8</th>
                        <th>9</th>
                        <th>10</th>
                        <th>11</th>
                        <th>12</th>
                        <th>13</th>
                        <th>14</th>
                        <th>15</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Up Cards</td>
                        <td></td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>8</td>
                        <td>10</td>
                        <td>20</td>
                        <td>40</td>
                        <td>60</td>
                        <td>100</td>
                        <td>150</td>
                        <td>300</td>
                        <td>450</td>
                        <td>750</td>
                    </tr>
                    <tr>
                        <td>Price Upgrade</td>
                        <td></td>
                        <td>52K</td>
                        <td>66K</td>
                        <td>86K</td>
                        <td>110K</td>
                        <td>140K</td>
                        <td>180K</td>
                        <td>210K</td>
                        <td>250K</td>
                        <td>280K</td>
                        <td>360K</td>
                        <td>440K</td>
                        <td>700K</td>
                        <td>2.5M</td>
                        <td>10M</td>
                    </tr>
                </tbody>
            </table>
            <table className="mei-li">
                <caption>Skills Table</caption>
                <thead>
                    <tr>
                        <th>Level</th>
                        <th>1</th>
                        <th>2</th>
                        <th>3</th>
                        <th>4</th>
                        <th>5</th>
                        <th>6</th>
                        <th>7</th>
                        <th>8</th>
                        <th>9</th>
                        <th>10</th>
                        <th>11</th>
                        <th>12</th>
                        <th>13</th>
                        <th>14</th>
                        <th>15</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Agility</td>
                        <td>4</td>
                        <td>6</td>
                        <td>8</td>
                        <td>9</td>
                        <td>11</td>
                        <td>13</td>
                        <td>15</td>
                        <td>15</td>
                        <td>17</td>
                        <td>20</td>
                        <td>21</td>
                        <td>23</td>
                        <td>24</td>
                        <td>26</td>
                        <td>27</td>
                    </tr>
                    <tr>
                        <td>Stamina</td>
                        <td>3</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                        <td>12</td>
                        <td>13</td>
                        <td>14</td>
                    </tr>
                    <tr>
                        <td>Serve</td>
                        <td>4</td>
                        <td>5</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>9</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                        <td>13</td>
                        <td>13</td>
                        <td>14</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <td>Volley</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>10</td>
                        <td>11</td>
                        <td>13</td>
                        <td>14</td>
                        <td>14</td>
                        <td>15</td>
                        <td>16</td>
                        <td>16</td>
                    </tr>
                    <tr>
                        <td>Forehand</td>
                        <td>4</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>12</td>
                        <td>13</td>
                        <td>14</td>
                        <td>15</td>
                        <td>16</td>
                        <td>17</td>
                        <td>18</td>
                        <td>19</td>
                    </tr>
                    <tr>
                        <td>Backhand</td>
                        <td>4</td>
                        <td>5</td>
                        <td>5</td>
                        <td>6</td>
                        <td>7</td>
                        <td>8</td>
                        <td>9</td>
                        <td>10</td>
                        <td>11</td>
                        <td>12</td>
                        <td>13</td>
                        <td>14</td>
                        <td>15</td>
                        <td>16</td>
                        <td>17</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Total Power</th>
                        <th>23</th>
                        <th>30</th>
                        <th>35</th>
                        <th>41</th>
                        <th>47</th>
                        <th>54</th>
                        <th>61</th>
                        <th>65</th>
                        <th>72</th>
                        <th>80</th>
                        <th>86</th>
                        <th>92</th>
                        <th>96</th>
                        <th>103</th>
                        <th>109</th>
                    </tr>
                </tfoot>
            </table>
            </div>
        </div>
    );
}

export default MeiLi;
